# AEnchants Config by Nomic
# More options coming very soon.
# Change the title used at the top of enchant signs.
# For enchant sign message, use {tier} and {enchant} variables.
# Enable if experience from ores is only given with experience enchant.
# Enable which books are given from the enchant signs.
# Decide what pieces books can be applied to.
# Pieces: Helmet, Chestplate, Leggings, Boots, Sword, Axe, Pickaxe, Shovel.
signTitle: '&1AEnchants'
signUseMessage: '&c&lAEnchants &8>> &bYou just purchased a &d{tier} &bAEnchant and got yourself a &e{enchant} &bEnchanted Book.'
notEnoughLevelsMessage: '&c&lAEnchants &8>> &eRequires at least &7{levels}&e levels.'
tooManyEnchantsMessage: '&c&lAEnchants &8>> &eItem has maximum number of enchants.'
fullInvMessage: '&c&lAEnchants &8>> &eInventory is full.'
addEnchantMessage: '&c&lAEnchants &8>> &bYou just applied &e{enchant} &bto an item.'
combineBookMessage: '&c&lAEnchants &8>> &bYou just made a &e{book} &bEnchanted Book.'
enabledExperienceEnchant: true
bookCombineCost: 4
tierOneApplyCost: 8
tierTwoApplyCost: 10
tierThreeApplyCost: 12
enchantLimit: 5
enabledBooks:
  enabledTierOnes:
  - Arc
  - Blaze
  - Bump
  - Feast
  - Fish
  - Health Boost
  - Implode
  - Leaps
  - Reborn
  - Replenish
  - Retreat
  - Scoot
  - Sunlight
  - Tipsy
  - Vanish
  - Weary
  - Archery
  - Confusion
  - Life
  - Lightning
  - Lights Out
  - Soul
  - Sword Block
  - Thunderous
  - Blast
  - Experience
  - Haste
  - Obsidian Destroyer
  - Anti Fog
  - Thief
  - Toughness
  enabledTierTwos:
  - Bump
  - Health Boost
  - Implode
  - Leaps
  - Reborn
  - Replenish
  - Retreat
  - Scoot
  - Tipsy
  - Vanish
  - Weary
  - Archery
  - Confusion
  - Life
  - Lightning
  - Lights Out
  - Soul
  - Thunderous
  - Blast
  - Experience
  - Haste
  - Obsidian Destroyer
  - Thief
  - Toughness
  enabledTierThrees:
  - Bump
  - Implode
  - Leaps
  - Reborn
  - Replenish
  - Retreat
  - Scoot
  - Tipsy
  - Vanish
  - Weary
  - Lightning
  - Thunderous
  - Experience
  - Haste
  - Obsidian Destroyer
  - Thief
  - Toughness
appliablePieces:
  Arc:
  - Chestplate
  - Leggings
  Blaze:
  - Chestplate
  - Leggings
  Bump:
  - Chestplate
  - Leggings
  Feast:
  - Helmet
  - Chestplate
  - Leggings
  Fish:
  - Helmet
  HealthBoost:
  - Helmet
  Implode:
  - Chestplate
  - Leggings
  Leaps:
  - Boots
  Reborn:
  - Chestplate
  - Leggings
  - Boots
  Replenish:
  - Chestplate
  - Leggings
  Retreat:
  - Chestplate
  - Leggings
  - Boots
  Scoot:
  - Boots
  Sunlight:
  - Helmet
  Tipsy:
  - Chestplate
  - Leggings
  Vanish:
  - Chestplate
  - Leggings
  Weary:
  - Chestplate
  - Leggings
  Confusion:
  - Sword
  Life:
  - Sword
  LightsOut:
  - Sword
  Soul:
  - Sword
  SwordBlock:
  - Sword
  Thunderous:
  - Sword
  Haste:
  - Pickaxe
  AntiFog:
  - Helmet
  Toughness:
  - Helmet
  - Chestplate
  - Leggings
  - Boots
enchantNames:
  Arc:
    one: '&bArc I'
  AntiFog:
    one: '&bAnti Fog I'
  Beast:
    one: '&bBeast I'
    two: '&eBeast II'
    three: '&cBeast III'
  Blaze:
    one: '&bBlaze I'
  Bump:
    one: '&bBump I'
    two: '&eBump II'
    three: '&cBump III'
  Feast:
    one: '&bFeast I'
  Fish:
    one: '&bFish I'
  HealthBoost:
    one: '&bHealth Boost I'
    two: '&eHealth Boost II'
  Implode:
    one: '&bImplode I'
    two: '&eImplode II'
    three: '&cImplode III'
  Leaps:
    one: '&bLeaps I'
    two: '&eLeaps II'
    three: '&cLeaps III'
  Reborn:
    one: '&bReborn I'
    two: '&eReborn II'
    three: '&cReborn III'
  Replenish:
    one: '&bReplenish I'
    two: '&eReplenish II'
    three: '&cReplenish III'
  Retreat:
    one: '&bRetreat I'
    two: '&eRetreat II'
    three: '&cRetreat III'
  Scoot:
    one: '&bScoot I'
    two: '&eScoot II'
    three: '&cScoot III'
  Sunlight:
    one: '&bSunlight I'
  Tipsy:
    one: '&bTipsy I'
    two: '&eTipsy II'
    three: '&cTipsy III'
  Toughness:
    one: '&bToughness I'
    two: '&eToughness II'
    three: '&cToughness III'
  Vanish:
    one: '&bVanish I'
    two: '&eVanish II'
    three: '&cVanish III'
  Weary:
    one: '&bWeary I'
    two: '&eWeary II'
    three: '&cWeary III'
  Archery:
    one: '&bArchery I'
    two: '&eArchery II'
  Confusion:
    one: '&bConfusion I'
    two: '&eConfusion II'
  Life:
    one: '&bLife I'
    two: '&eLife II'
  Lightning:
    one: '&bLightning I'
    two: '&eLightning II'
    three: '&cLightning III'
  LightsOut:
    one: '&bLights Out I'
    two: '&eLights Out II'
  Soul:
    one: '&bSoul I'
    two: '&eSoul II'
  SwordBlock:
    one: '&bSword Block I'
  Thief:
    one: '&bThief I'
    two: '&eThief II'
    three: '&cThief III'
  Thunderous:
    one: '&bThunderous I'
    two: '&eThunderous II'
    three: '&cThunderous III'
  Blast:
    one: '&bBlast I'
    two: '&eBlast II'
  Experience:
    one: '&bExperience I'
    two: '&eExperience II'
    three: '&cExperience III'
  Haste:
    one: '&bHaste I'
    two: '&eHaste II'
    three: '&cHaste III'
  ObsidianDestroyer:
    one: '&bObsidian Destroyer I'
    two: '&eObsidian Destroyer II'
    three: 'cObsidian Destroyer III'
